language: node_js
node_js:
    - "lts/*"
cache: yarn
install:
    - yarn
script:
   - yarn blog:build
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: ./docs/.vuepress/dist/
    target-branch: gh-pages
    verbose: true
    on:
      branch: master